version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: altairis-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_password123!"
      MSSQL_TCP_PORT: "1433"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433'"]
      timeout: 5s
      retries: 10
    networks:
      - altairis-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: altairis-backend
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=AltairisDB;User Id=sa;Password=Your_strong_password123!;TrustServerCertificate=True;"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - altairis-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: altairis-frontend
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:5000"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - altairis-net

networks:
  altairis-net:
    driver: bridge

